version: '3.9'

services:
  app:
    build: .
    image: ace-vba-app
    depends_on:
      - db
    container_name: ace_vba_app
    environment:
      - SPRING_DATASOURCE_URL=jdbc:postgresql://db:5432/ace_vba_db
      - SPRING_DATASOURCE_USERNAME=postgres
      - SPRING_DATASOURCE_PASSWORD=postgres
    ports:
      - "8080:8080"

  db:
    image: postgres
    container_name: ace_vba_db
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_DB=ace_vba_db
    ports:
          - '5432:5432'
    volumes:
      - ./postgres-data:/var/lib/postgresql/data