version: '3.9'

services:
  api:
    build: .
    image: ace_vba_api
    container_name: ace_vba_api
    depends_on:
      db:
        condition: service_healthy
    environment:
      - SPRING_DATASOURCE_URL=jdbc:postgresql://db:5432/${DB_NAME}
      - SPRING_DATASOURCE_USERNAME=${DB_USER}
      - SPRING_DATASOURCE_PASSWORD=${DB_PASSWORD}
    ports:
      - "8080:8080"

  db:
    image: postgres
    restart: always
    container_name: ace_vba_db
    environment:
      - POSTGRES_USER=${DB_USER}
      - POSTGRES_PASSWORD=${DB_PASSWORD}
      - POSTGRES_DB=${DB_NAME}
    ports:
          - '5432:5432'
    volumes:
      - .docker/postgres-data:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -d ace-vba-db -U ace-vba"]
      interval: 5s
      timeout: 5s
      retries: 5
